Repository MindReport/MindReport-server, pull requests merged in 2024-03, with the labels that each got.

#5 [CI/2] Github Action 스크립트 수정 & Beanstalk 애플리케이션 구성
  .ebextensions/00-makeFiles.config
  .github/workflows/mindreport-cd.yml
  .platform/nginx/nginx.conf
  Procfile
Labels: :construction_worker: ci

#8 [CI/3] build gradle & time-out 수정
  .github/workflows/mindreport-cd.yml
  build.gradle
Labels: :construction_worker: ci

#10 [Docs/1] Swagger 설정
  build.gradle
  src/main/java/com/mindreport/server/config/SwaggerConfig.java
  src/main/java/com/mindreport/server/controller/TestController.java
Labels: :memo: documentation

#14 [Feat/11] API 응답 통일, 공통 에러 처리 구현
  build.gradle
  src/main/java/com/mindreport/server/base/ApiResponse.java
  src/main/java/com/mindreport/server/base/code/BaseCode.java
  src/main/java/com/mindreport/server/base/code/BaseErrorCode.java
  src/main/java/com/mindreport/server/base/code/ErrorReasonDTO.java
  src/main/java/com/mindreport/server/base/code/ReasonDTO.java
  src/main/java/com/mindreport/server/base/code/status/ErrorStatus.java
  src/main/java/com/mindreport/server/base/code/status/SuccessStatus.java
  src/main/java/com/mindreport/server/base/exception/ExceptionAdvice.java
  src/main/java/com/mindreport/server/base/exception/GeneralException.java
  src/main/java/com/mindreport/server/base/exception/handler/TempHandler.java
  src/main/java/com/mindreport/server/controller/TestController.java
Labels: :sparkles: feature

#13 👷Ci: Health Check API 설정
  build.gradle
  src/main/resources/application.properties
Labels: :construction_worker: ci
